### ISSUE TITLE
Issues reproducing results

### ISSUE THREAD

**Issue by NOlivier-H** [jgkwak95/SURF-GAN#10]
Hello, thanks for your work, and for making your code available.
I am having issues reproducing your results on CelebA, the network seems to converge up to around iteration 15k, but then the image quality degrades until becoming nothing recognizable.
I used the command `python train_surf.py --output_dir exp_name --curriculum CelebA_single`, with nothing changed from your code.
The python env was created using your instructions in "Create virtual environment".
I ran the training process 3 times, and consistently obtained this result.
Here are random samples at 15k, and 40k:
![15k](https://user-images.githubusercontent.com/122534358/212065406-da657a8b-eca5-4dbe-b46a-36642d1d7812.png)
![40k](https://user-images.githubusercontent.com/122534358/212065484-be6b0a62-9059-4bd1-bf2d-505c52d8d9ca.png)

**Comment by jgkwak95** [comment]
Hi @NOlivier-H , Thanks for you attention. 

I just checked the train and curriculum files, I found that the batch size (now 14) is wrong.
For the first stage, I used the batch_size: 56 (not 14) At each stage, the batch size is multiplied by 1/4.
I forgot to change the original value after experimenting with my code under different conditions. 

Therefore, please  change the value of batch_size of the first stage in curriculums.py-CelebA_single.
Generally, with higher batch_size, you can expect higher quality. so set the maximum batch size for your GPU.

**Comment by jgkwak95** [comment]
I changed batch_size of the first stage 14-->56
