### ISSUE TITLE
How to realize 3d controllable editing in your demo?

### ISSUE THREAD

**Issue by xuanyuzhang21** [jgkwak95/SURF-GAN#2]
Thanks for your great work. Could you tell me how to realize 3d controllable face editing via the code in your project? Thanks a lot.

**Comment by jgkwak95** [comment]
Hi! I'm not sure which model you referred to: SURF-GAN or 3D-controllable StyleGAN.

If the former, see 'discover_semantics.py' and check which att belongs to which layer & dimension.
After that, run 'render_video_semantics.py' by giving target LiDj to control the attribute.
In the case of 3D-controllable StyleGAN, the codes are not released. I'm not sure if this will be published or not, but if it does, it will be published in other repo. to prevent env conflicts or other issues.  Thank you.
