### ISSUE TITLE
 2D profile face -> a frontal face

### ISSUE THREAD

**Issue by hxl835097324** [jgkwak95/SURF-GAN#6]
Hi @jgkwak95,
thanks a lot for sharing the code for your work, it is very interesting. Can we use a 2D profile face to acquire a frontal face by this work?

Thank you very much !

**Comment by jgkwak95** [comment]
@hxl835097324  Thanks for your attention! 

Yes, our latent mapper performs frontalization task (in StyleGAN latent space), but we didnt upload that.
