### ISSUE TITLE
Dead pretrained model link

### ISSUE THREAD

**Issue by NOlivier-H** [jgkwak95/SURF-GAN#9]
Hi, thank you for your work, and sharing your code and model.
Unfortunately, the google drive link to your pretrained model seems dead right now, it gives a "Not found" error.

**Comment by jgkwak95** [comment]
Hi @NOlivier-H , 

The download link is blocked due to change of our school's mail server, so it will probably take few days.

**Comment by NOlivier-H** [comment]
Okay I see, thank you for your fast reply !

**Comment by jgkwak95** [comment]
Sorry for late reply.

I changed the link.

**Comment by HanGuangXin** [comment]
@NOlivier-H Hi there! 
The model link seems dead again. I'm wondering if you could share it? It would be kind of you~
